/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GraphElem } from "./global/model";
export namespace Components {
    interface UiPercentageBar {
        "data": GraphElem[];
    }
}
declare global {
    interface HTMLUiPercentageBarElement extends Components.UiPercentageBar, HTMLStencilElement {
    }
    var HTMLUiPercentageBarElement: {
        prototype: HTMLUiPercentageBarElement;
        new (): HTMLUiPercentageBarElement;
    };
    interface HTMLElementTagNameMap {
        "ui-percentage-bar": HTMLUiPercentageBarElement;
    }
}
declare namespace LocalJSX {
    interface UiPercentageBar {
        "data"?: GraphElem[];
    }
    interface IntrinsicElements {
        "ui-percentage-bar": UiPercentageBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-percentage-bar": LocalJSX.UiPercentageBar & JSXBase.HTMLAttributes<HTMLUiPercentageBarElement>;
        }
    }
}
